"""empty message

Revision ID: 03360c370aab
Revises: 854114187d73
Create Date: 2018-03-30 19:44:32.037076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03360c370aab'
down_revision = '854114187d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_fornece_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fornecedore_fornece_produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedore_fornece_produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fornecedor', sa.INTEGER(), nullable=True),
    sa.Column('produto', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fornecedor_fornece_produto')
    # ### end Alembic commands ###
