"""empty message

Revision ID: 27a8e76c38f6
Revises: 
Create Date: 2018-03-30 21:37:15.268513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a8e76c38f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_fornece_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=50), nullable=True),
    sa.Column('nomeFantasia', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('cnpj', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_do_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('fornecedor1', sa.Integer(), nullable=True),
    sa.Column('fornecedor2', sa.Integer(), nullable=True),
    sa.Column('fornecedor3', sa.Integer(), nullable=True),
    sa.Column('valor_fornecedor1', sa.Numeric(), nullable=True),
    sa.Column('valor_fornecedor2', sa.Numeric(), nullable=True),
    sa.Column('valor_fornecedor3', sa.Numeric(), nullable=True),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor1'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['fornecedor2'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['fornecedor3'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_do_pregao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_referencia', sa.Numeric(), nullable=True),
    sa.Column('pregao', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.Column('fornecedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pregao'], ['pregoes.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_tem_item_do_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.Column('itens_do_pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itens_do_pedido'], ['itens_do_pedido.id'], ),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('requisitante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requisitante'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregao_tem_item_do_pregao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregao', sa.Integer(), nullable=True),
    sa.Column('itens_do_pregao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itens_do_pregao'], ['itens_do_pregao.id'], ),
    sa.ForeignKeyConstraint(['pregao'], ['pregoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.Column('item_pregao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_pregao'], ['itens_do_pregao.id'], ),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('catmat', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catmat')
    )
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('setor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setor'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('setores')
    op.drop_table('produtos')
    op.drop_table('pregoes')
    op.drop_table('pregao_tem_item_do_pregao')
    op.drop_table('pedidos')
    op.drop_table('pedido_tem_item_do_pedido')
    op.drop_table('itens_do_pregao')
    op.drop_table('itens_do_pedido')
    op.drop_table('fornecedores')
    op.drop_table('fornecedor_fornece_produto')
    # ### end Alembic commands ###
