"""empty message

Revision ID: dd9b37ee5c08
Revises: 77e34d225297
Create Date: 2018-03-25 13:59:32.973199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9b37ee5c08'
down_revision = '77e34d225297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('tipo2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'tipo2')
    # ### end Alembic commands ###
